In [12]:
from torch import tensor
import torch

In [9]:
tt = tensor([[1, 2], [5,6]]) 
tt

tensor([[1, 2],
        [5, 6]])

In [10]:
tt * 5

tensor([[ 5, 10],
        [25, 30]])

In [11]:
tt * tensor([1,3])

tensor([[ 1,  6],
        [ 5, 18]])

In [16]:
torch.zeros([2,3], dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [18]:
tt.item()

ValueError: only one element tensors can be converted to Python scalars

In [20]:
torch.device()

TypeError: Device() received an invalid combination of arguments - got (), but expected one of:
 * (torch.device device)
 * (str type, int index)


In [22]:
[torch.cuda.device(i) for i in range(torch.cuda.device_count())]

In [23]:
torch.cuda.device_count()

1